### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by RobinW99** [jeetee/MuseScore_TempoChanges#5]
Dear @jeetee ,

For me Tempo Changes for Musescore 2.1 does not work at all.
I have just downloaded Musescore 2.0.2, even here your plugin does not work.
What happens:
I fill in all the data and click on apply and then nothing happens at all.

Can you help me?

**Comment by jeetee** [comment]
It might sound as a silly question, but are you sure you have selected a range first (blue rectangle around the notes)? Otherwise the plugin doesn't know where to apply the requested change and will do nothing at all, just like you described.

---
Het lijkt misschien een stomme vraag, maar ben je zeker dat je eerst een bereikselectie hebt gemaakt (blauwe rechthoek rondom de gewenste noten)? Indien niet, weet de plugin niet waar de tempowisseling moet toegepast worden en doet die inderdaad niets, net zoals je omschrijft.
Zie ook de schermafbeelding op https://musescore.org/en/project/tempochanges

**Comment by RobinW99** [comment]
Oh, wat ben ik weer dom bezig... Ik heb inderdaad precies dat vergeten te doen.
Bedankt voor het helpen!

**Comment by jeetee** [comment]
Geen probleem, waren alle problemen maar zo makkelijk op te lossen ;)

**Comment by RobinW99** [comment]
Beste @jeetee,
Sinds MuseScore 3.0 kan ik uw plugin niet meer gebruiken.
Is dit iets wat u kunt oplossen?
De plugin komt überhaupt niet tussen mijn plugins te staan, ookal heb ik deze wel geactiveerd in het pluginbeheer.
Groeten, Robin

**Comment by jeetee** [comment]
Dag Robin,

MuseScore 3 is gereleased zonder plugin-ondersteuning. De ontwikkelaars plannen deze terug te activeren in een update in het eerste deel van 2019. Van zodra dat stabiliseert in het ontwikkeltraject plan ik in om deze plugin uit te breiden zodat deze ook in versie 3 zal werken.

Daartoe is issue #8 aangemaakt.
